I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 603, in script
    "Как и предложила Настя, ребята приехали туда,\n где живут девчата – микрорайон "Щербинки-3"."
Exception: Say has image attributes ('Щербинки-3',), but there's no image tag associated with the speaking character.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 603, in script
    "Как и предложила Настя, ребята приехали туда,\n где живут девчата – микрорайон "Щербинки-3"."
  File "C:\Users\Андрей Варфоломеев\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Андрей Варфоломеев\Desktop\renpy-8.1.3-sdk\renpy\exports.py", line 1472, in say
    renpy.store.say(who, what, *args, **kwargs)
  File "C:\Users\Андрей Варфоломеев\Desktop\renpy-8.1.3-sdk\renpy\defaultstore.py", line 418, in say
    who(what, interact=interact, *args, **kwargs)
  File "C:\Users\Андрей Варфоломеев\Desktop\renpy-8.1.3-sdk\renpy\character.py", line 1290, in __call__
    old_attr_state = self.handle_say_attributes(False, interact)
  File "C:\Users\Андрей Варфоломеев\Desktop\renpy-8.1.3-sdk\renpy\character.py", line 1109, in handle_say_attributes
    if self.resolve_say_attributes(predicting, attrs):
  File "C:\Users\Андрей Варфоломеев\Desktop\renpy-8.1.3-sdk\renpy\character.py", line 1035, in resolve_say_attributes
    raise Exception("Say has image attributes %r, but there's no image tag associated with the speaking character." % (attrs,))
Exception: Say has image attributes ('Щербинки-3',), but there's no image tag associated with the speaking character.

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Сохры 1.01
Fri Jan 17 23:32:37 2025
